### ISSUE TITLE
Signature failures on large bodies

### ISSUE THREAD

**Issue by brewneaux** [AllocZero/EfficientDynamoDb#203]
When doing a BatchWrite with large items, you sometimes get a "The request signature we calculated does not match the signature you provided" error back from AWS.

**Comment by firenero** [comment]
Sorry for the delay @brewneaux. Your fix is merged and currently available in the pre-release version `0.9.14-alpha.0.6`.

**Comment by wjax** [comment]
Hi,

I am seeing this

**Comment by wjax** [comment]
By the way, this is using 0.9.16
@firenero

**Comment by firenero** [comment]
@wjax In theory it was solved and 0.9.16 should not be affected but there could be another source for the issue. It will be tricky to troubleshoot without reproducible example. What is the difference between your local environment vs ECS container? I'm mainly interested if .NET version is exactly the same and if you're using macOS or Windows locally.

**Comment by wjax** [comment]
ECS is running the official net8 container, from dockerfile:
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

In local, it is a windows machine with dotnet8 sdk.

The thing is that it has been happening also with net6 (as we discovered the bug some weeks ago just before upgrading to net8)

Any clues on what we could try or where we could log to narrow down the issue?


Many thanks

**Comment by firenero** [comment]
@wjax my only idea so far is that the issue is related to compression. It seems that DynamoDB [adds checksum of the compressed body](https://github.com/aws/aws-sdk-js/issues/405#issuecomment-62284496) but we use automatic decompression that probably validates the uncompressed response which seems to be a common error in SDKs. For batch writes, DynamoDB _might_ expect gzip compressed body as well that I think we don't do. Some ideas to try:
1. Set value in [this line](https://github.com/AllocZero/EfficientDynamoDb/blob/686e6c20dfbf99dcf8294bc64c273331bd47d9de/src/EfficientDynamoDb/Configs/Http/DefaultHttpClientFactory.cs#L16) to `DecompressionMethods.None` and see if the error still happens.
2. Put a breakpoint [here](https://github.com/AllocZero/EfficientDynamoDb/blob/80ea4372f1c4b82a83247d562dde3048789f63c7/src/EfficientDynamoDb/Internal/HttpApi.cs#L53) and check if request headers have `Content-Encoding: gzip` or similar and if request content is compressed for some reason.

**Comment by wjax** [comment]
Thanks for the info.
We are seeing this behaviour:

![Image](https://github.com/user-attachments/assets/72e878cf-b41f-4053-8014-ff650877fa76)

We see some throttling exceptions (those of the retries) and then the signature error. Could it be that the signature error is linked to a previously failed attemp to batch write some items?
The throtlling error is another story that we do not understand (WCUs not going over 50!)

Details of the throttling:

![Image](https://github.com/user-attachments/assets/78ca4968-d248-4039-940d-d793f418fe49)

Thanks again for the help

**Comment by wjax** [comment]
Hello again,

Issue still persists but do not happen all the times. It is happening only in production now.
There is some interesting behaviour that should be related:

Context: We use default retry behaviour, so it should retry in a throtling error with a 50ms base and exponential backoff as especified in the jitter retry.
However, if you see at the capture of previous comment, **the first 5 "request failed" are actually throtling exceptions with 0 MILLISECONDS separation**. How is it possible? All of the 5 tries fails and the next errors are "signature" errors.

So how can it be that the retries are being executed one after the other without awaiting?
And then, the final signature error, could be related to the previous "erroneous" behaviour?

Thanks

**Comment by mmaravidal** [comment]
Hi @firenero ,

I have been working on this issue and I can provide some additional information.

We are experiencing issues with large batch operations, such as 10k put documents. Our scenario is as follows:

* We have a DynamoDB table with a partition key (PK) and 3 global secondary indexes (GSI).
* The table is in Pay-Per-Request mode, with no throughput limits.
* We are using .NET 8.
* We have a dependency on EfficientDynamoDb 0.9.16 and EfficientDynamoDb.Credentials.AWSSDK 0.9.3.
* We have a dependency on Microsoft.IO.RecyclableMemoryStream 3.0.1.

When DynamoDB returns a ThrottlingException, the next retry (within HttpApi.SendAsync) always fails with a Signature exception. I wrote an isolated app that demonstrates this issue. I tried to debug some code, and the computed signature looks fine, but honestly, it was hard to debug and could be wrong.

The same code, referencing Microsoft.IO.RecyclableMemoryStream 1.3.6, **does not show this behavior**.
The same code, referencing local projects EfficientDynamoDb and EfficientDynamoDb.Credentials.AWSSDK (cloned this repo and checked out the branch effddb-v0.9.16), **does not show this behavior** (this one is mind-blowing for me 😄).

Help and guidance will be much appreciated, as we use this library in a very critical path in our application.

The code I am using to test this is as follows:

```csharp
using Amazon.Runtime;
using EfficientDynamoDb;
using EfficientDynamoDb.Attributes;
using EfficientDynamoDb.Configs;
using EfficientDynamoDb.Configs.Retries;
using EfficientDynamoDb.Credentials.AWSSDK;
using Spectre.Console;

namespace Demo;

public static class Program
{
    private static readonly IAnsiConsole Console = AnsiConsole.Create(new AnsiConsoleSettings());

    public static async Task Main()
    {
        const int iterations = 100;
        const int items = 10_000;
        
        var context = CreateEfficientContext(false);

        var tasks = Enumerable.Range(0, iterations)
            .Select(async x =>
            {
                var chunks = CreateEntities(x, items)
                    .Select(Batch.PutItem)
                    .ToArray()
                    .Chunk(25)
                    .Select((chunk, i) => (chunk, i));

                foreach (var (chunk, i) in chunks)
                {
                    try
                    {
                        await context.BatchWrite()
                            .WithItems(chunk)
                            .ExecuteAsync();

                        Console.MarkupLine($"[gray]Create Batch[/] #{x}/{i} [green]Done[/]");
                    }
                    catch (Exception e)
                    {
                        Console.MarkupLine($"[gray]Create Batch[/] #{x}/{i} [red]Failed[/]");
                        Console.Write(e.GetRenderable());
                    }
                }
            })
            .ToArray();
        
        var task = Task.WhenAll(tasks);

        try
        {
            await task;
            Console.MarkupLine("Done!");
        }
        catch (Exception e)
        {
            Console.Write(task.Exception!.GetRenderable());
        }
    }

    static DynamoDbContext CreateEfficientContext(bool useEmulator = false)
    {
        var regionEndpoint = useEmulator
            ? RegionEndpoint.Create("eu-west-2", "http://localhost:8000")
            : RegionEndpoint.EUWest2;
        
        var credentials = FallbackCredentialsFactory.GetCredentials();

        var config = new DynamoDbContextConfig(
            regionEndpoint,
            credentials.ToCredentialsProvider());

        config.RetryStrategies.ProvisionedThroughputExceededStrategy = RetryStrategyFactory.Jitter(
            baseDelayMs: 1_000,
            maxRetriesCount: 15);

        return new DynamoDbContext(config);
    }

    static IEnumerable<Permission> CreateEntities(int iteration, int items)
    {
        return Enumerable.Range(0, items)
            .Select(i => new Permission
            {
                Pk = $"Permission#{iteration}",
                Sk = $"Permission#{i}",
                Gsi1Pk = $"Gsi1#{iteration}",
                Gsi1Sk = $"Gsi1#{i}",
                Gsi2Pk = $"Gsi2#{iteration}",
                Gsi2Sk = $"Gsi2#{i}",
                Gsi3Pk = $"Gsi3#{iteration}",
                Gsi3Sk = $"Gsi3#{i}"
            });
    }

    [DynamoDbTable("Permissions_ThroughputTest")]
    record Permission
    {
        [DynamoDbProperty("Pk")]
        public required string Pk { get; init; }

        [DynamoDbProperty("Sk")]
        public required string Sk { get; init; }

        [DynamoDbProperty("Gsi1Pk")]
        public required string Gsi1Pk { get; init; }

        [DynamoDbProperty("Gsi1Sk")]
        public required string Gsi1Sk { get; init; }

        [DynamoDbProperty("Gsi2Pk")]
        public required string Gsi2Pk { get; init; }

        [DynamoDbProperty("Gsi2Sk")]
        public required string Gsi2Sk { get; init; }

        [DynamoDbProperty("Gsi3Pk")]
        public required string Gsi3Pk { get; init; }

        [DynamoDbProperty("Gsi3Sk")]
        public required string Gsi3Sk { get; init; }
    }
}
```

Thank you in advance! 😄

**Comment by firenero** [comment]
Thanks for detailed example @mmaravidal. I have a couple questions to help me investigate it further.

Could you try disabling GZip compression in the environment with the error to see if it mitigates the issue? To disable GZip you need to replace the [DynamoDbContextConfig.HttpClientFactory](https://github.com/AllocZero/EfficientDynamoDb/blob/993a963137c66fb84e4ec657a40ab245b0b3e87a/src/EfficientDynamoDb/DynamoDbContextConfig.cs#L24) with your own implementation. The implementation is basically the same as [DefaultHttpClientFactory](https://github.com/AllocZero/EfficientDynamoDb/blob/686e6c20dfbf99dcf8294bc64c273331bd47d9de/src/EfficientDynamoDb/Configs/Http/DefaultHttpClientFactory.cs#L16) but use `DecompressionMethods.None` instead of `DecompressionMethods.GZip`.

> The same code, referencing Microsoft.IO.RecyclableMemoryStream 1.3.6, does not show this behavior.

Do you mean that if you downgrade the `Microsoft.IO.RecyclableMemoryStream` from 3.0.1 to 1.3.6 in your affected environment the issue goes away?

**Comment by mmaravidal** [comment]
We already tried with a custom HttpClientFactory disabling GZip compression with no changes.

That's it. After downgrading Microsoft's package we can not reproduce the issue with the provided code. But we can not downgrade it in production as it is a dependency of our own code.

**Comment by wjax** [comment]
Hi @firenero 

Did you have a chance to look at this issue?
Can we help in any way? @mmaravidal and myself have run out of ideas

**Comment by firenero** [comment]
@wjax @mmaravidal #265 contains the fix to the issue. Could you try updating EfficientDynamoDb to 0.9.17 and verify that the fix works for you?

**Comment by mmaravidal** [comment]
Thank you @firenero !

That one worked in the repro scenario. We will deploy the fix soon and validate it in our production environment, but I think you can close the issue.

Thanks for your help! 😊

**Comment by wjax** [comment]
I am very sorry to say that it seems that problem is not completely fixed:

![Image](https://github.com/user-attachments/assets/0ece0de9-e6aa-4db0-a6f9-9285f5149d99)

We can no longer reproduce it with our throughput test and we see it only happening in production. It happens all the times in a given situation.
Not much to say. We will try to chase it but being totally frank, we may eventually port our client to use official sdk.

Thanks again for the help!

**Comment by firenero** [comment]
@wjax Sorry to hear that. We've spent several hours troubleshooting it today and have a hunch that the issue is related to how dotnet handles http requests on linux. Several questions to help us debug this one:
1. What's version of linux is running in your production environment?
2. Did you run your repro example in the same linux version? If not, can you try it? 
3. Can you install a pre-release version of EfficientDynamoDb in your production environment if we publish one with potential fix?

**Comment by wjax** [comment]
We were feeling too that the issue laid on some implementation in Linux. We
were betting on recyclable stream lib.

It’s great (thank you so much) that you have a clue of were the problem may
be.

I have tried the repo example in WSL2 in windows. I can run it in the same
docker image that we use in production later today.
In WSL2, problem was not there (run it three times I think)

Since your last patch (resetting stream position to 0) it has been
difficult to make it fail. In fact it only fails in prod, not even in our
dev account (exactly the same as infra come from CDK)
I was yesterday copying the case that fails in prod to our dev account. It
is a case were we write 130k entities of about 1kbyte each.
The first run in our dev account did not fail 😩. Will test again today.

We would like to understand the problem (just curiosity). Is this happening
to official AWS SDK too? Do they have some workaround in case running is is
Linux?

As for testing prerelease version. We really want to make it work. Both
because we love your library and also to avoid having to rewrite a good
amount of things.
We would like to understand what the possible failure cases would be in the
prerelease version. Problems could happen both in Read and write
operations? For us, read operations happen all time and thus are more
critical, write operations happens less frequently and we could maybe
manage them.
So yes. We could try prerelease in prod. However I hope to be able to make
it fail today in our dev account.

**Comment by wjax** [comment]
Guys, 

I have to deeply apologize. We have made an error in our commits and production was running with 0.9.16
Really sorry!

**Comment by firenero** [comment]
@wjax I'm glad and disappointed to hear that at the same time 🙂 But it's great that you could confirm that the issue is indeed fixed.
